### ISSUE TITLE
v0.2.0 make, cannot stat './/supa_audit--0.1.0.sql'

### ISSUE THREAD

**Issue by ZeroDeltaAlpha** [supabase/supa_audit#43]
# Bug report

## Describe the bug
If you checkout out the tagged v0.2.0 release `make install` will fail, with the error `/usr/bin/install: cannot stat './/supa_audit--0.1.0.sql': No such file or directory`

## To Reproduce

1. do `git checkout tags/v0.2.0`
2. Run make install

## Expected behavior

A clean build to be produced.

## Additional context
I could fix the issue by using the value from `main` which is `DATA = $(wildcard *--*.sql)`.

**Comment by olirice** [comment]
thanks!

This bug was resolved in #16

I just pushed `v0.3.0`, the current version, as a tag [here](https://github.com/supabase/supa_audit/releases/tag/v0.3.0) so please use that one instead

**Comment by sebastianwebber** [comment]
Hello @olirice!

It looks like that the problem persists:

```bash
bash-4.4$ git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/${EXTENSION_NAME}"
Cloning into '/build/supa_audit'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 41 (delta 10), reused 20 (delta 3), pack-reused 0
Receiving objects: 100% (41/41), 15.00 KiB | 166.00 KiB/s, done.
Resolving deltas: 100% (10/10), done.
Note: switching to 'ba0553311b4363f2bef6ec0b8801c81010a8c1dc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

bash-4.4$ cd supa_audit/
bash-4.4$ make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fcf-protection -fPIC -shared -o supa_audit.so  -L/usr/lib/postgresql/12.11/lib   -L/usr/lib64  -Wl,--as-needed -Wl,-rpath,'/usr/lib/postgresql/12.11/lib',--enable-new-dtags  
/usr/bin/mkdir -p '/usr/lib/postgresql/12.11/lib'
/usr/bin/mkdir -p '/usr/share/postgresql/12.11/extension'
/usr/bin/mkdir -p '/usr/share/postgresql/12.11/extension'
/usr/bin/install -c -m 755  supa_audit.so '/usr/lib/postgresql/12.11/lib/supa_audit.so'
/usr/bin/install -c -m 644 .//supa_audit.control '/usr/share/postgresql/12.11/extension/'
/usr/bin/install -c -m 644 .//supa_audit--0.1.0--0.2.0.sql .//supa_audit--0.2.3--0.3.0.sql .//supa_audit--0.2.2--0.2.3.sql .//supa_audit--0.2.1--0.2.2.sql .//supa_audit--0.2.0--0.2.1.sql .//supa_audit--0.3.0.sql  '/usr/share/postgresql/12.11/extension/'
/usr/bin/mkdir -p '/usr/lib/postgresql/12.11/lib/bitcode/supa_audit'
/usr/bin/mkdir -p 
mkdir: missing operand
Try 'mkdir --help' for more information.
make: *** [/usr/lib/postgresql/12.11/lib/pgxs/src/makefiles/pgxs.mk:234: install] Error 1
``` 

I'm missing something?

**Comment by olirice** [comment]
that appears to be a different error
```
/usr/bin/mkdir -p 
mkdir: missing operand
```

I wasn't able to reproduce the error locally. Would you be able to reproduce this as a Dockerfile so I can take a look at the environment?

**Comment by sebastianwebber** [comment]
This is not se same image, but get the same output:

```Dockerfile
FROM quay.io/ongres/postgres-build:v12

USER postgres
WORKDIR /build

RUN git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/supa_audit"
WORKDIR /build/supa_audit

RUN make install
```

The full output is something like this:

```shell
❯ cat <<EOF | docker build -t supa_audit:foo -
FROM quay.io/ongres/postgres-build:v12

USER postgres
WORKDIR /build

RUN git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/supa_audit"
WORKDIR /build/supa_audit

RUN make install

EOF
[+] Building 1.2s (8/8) FINISHED                                                                                                                                             
 => [internal] load build definition from Dockerfile                                                                                                                    0.1s
 => => transferring dockerfile: 256B                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                       0.1s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [internal] load metadata for quay.io/ongres/postgres-build:v12                                                                                                      0.8s
 => [1/5] FROM quay.io/ongres/postgres-build:v12@sha256:66c28775e9667f2441b19691f95be75bf0454782e4947d31c33c650f516faa3e                                                0.0s
 => CACHED [2/5] WORKDIR /build                                                                                                                                         0.0s
 => CACHED [3/5] RUN git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/supa_audit"                                                        0.0s
 => CACHED [4/5] WORKDIR /build/supa_audit                                                                                                                              0.0s
 => ERROR [5/5] RUN make install                                                                                                                                        0.3s
------                                                                                                                                                                       
 > [5/5] RUN make install:                                                                                                                                                   
#8 0.224 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fcf-protection -fPIC -shared -o supa_audit.so  -L/usr/lib/postgresql/12.9/lib   -L/usr/lib64  -Wl,--as-needed -Wl,-rpath,'/usr/lib/postgresql/12.9/lib',--enable-new-dtags  
#8 0.234 /usr/bin/mkdir -p '/usr/lib/postgresql/12.9/lib'
#8 0.235 /usr/bin/mkdir -p '/usr/share/postgresql/12.9/extension'
#8 0.236 /usr/bin/mkdir -p '/usr/share/postgresql/12.9/extension'
#8 0.237 /usr/bin/install -c -m 755  supa_audit.so '/usr/lib/postgresql/12.9/lib/supa_audit.so'
#8 0.238 /usr/bin/install -c -m 644 .//supa_audit.control '/usr/share/postgresql/12.9/extension/'
#8 0.239 /usr/bin/install -c -m 644 .//supa_audit--0.1.0--0.2.0.sql .//supa_audit--0.2.3--0.3.0.sql .//supa_audit--0.2.2--0.2.3.sql .//supa_audit--0.2.1--0.2.2.sql .//supa_audit--0.2.0--0.2.1.sql .//supa_audit--0.3.0.sql  '/usr/share/postgresql/12.9/extension/'
#8 0.240 /usr/bin/mkdir -p '/usr/lib/postgresql/12.9/lib/bitcode/supa_audit'
#8 0.241 /usr/bin/mkdir -p 
#8 0.242 mkdir: missing operand
#8 0.242 Try 'mkdir --help' for more information.
#8 0.242 make: *** [/usr/lib/postgresql/12.9/lib/pgxs/src/makefiles/pgxs.mk:234: install] Error 1
------
executor failed running [/bin/sh -c make install]: exit code: 2
```

**Comment by sebastianwebber** [comment]
@olirice it looks like the solution is already present in  https://github.com/supabase/supa_audit/issues/36#issue-1210028572 .

Adding the `with_llvm=no` it works:

```shell
cat <<EOF | docker build -t supa_audit:foo -
∙ FROM quay.io/ongres/postgres-build:v12

USER postgres
WORKDIR /build

RUN git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/supa_audit"
WORKDIR /build/supa_audit

RUN make install USE_PGXS=1 with_llvm=no
∙ 
∙ EOF
Sending build context to Docker daemon  2.048kB
Digest: sha256:66c28775e9667f2441b19691f95be75bf0454782e4947d31c33c650f516faa3e
Status: Downloaded newer image for quay.io/ongres/postgres-build:v12
 ---> ad4fec9e16ef
Step 2/6 : USER postgres
 ---> Running in 7fc4f03b4f63
Removing intermediate container 7fc4f03b4f63
 ---> db8cbb6f78a0
Step 3/6 : WORKDIR /build
 ---> Running in 69999b0d29f8
Removing intermediate container 69999b0d29f8
 ---> 6c11a81f02ac
Step 4/6 : RUN git clone  -b "v0.3.0" --depth 1 https://github.com/supabase/supa_audit "/build/supa_audit"
 ---> Running in e7c2614398ac
Cloning into '/build/supa_audit'...
Note: switching to 'ba0553311b4363f2bef6ec0b8801c81010a8c1dc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Removing intermediate container e7c2614398ac
 ---> f35bcde6566f
Step 5/6 : WORKDIR /build/supa_audit
 ---> Running in 9aeea4d13131
Removing intermediate container 9aeea4d13131
 ---> 61018c06a099
Step 6/6 : RUN make install USE_PGXS=1 with_llvm=no
 ---> Running in 488e3a5126f6
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fcf-protection -fPIC -shared -o supa_audit.so  -L/usr/lib/postgresql/12.9/lib   -L/usr/lib64  -Wl,--as-needed -Wl,-rpath,'/usr/lib/postgresql/12.9/lib',--enable-new-dtags  
/usr/bin/mkdir -p '/usr/lib/postgresql/12.9/lib'
/usr/bin/mkdir -p '/usr/share/postgresql/12.9/extension'
/usr/bin/mkdir -p '/usr/share/postgresql/12.9/extension'
/usr/bin/install -c -m 755  supa_audit.so '/usr/lib/postgresql/12.9/lib/supa_audit.so'
/usr/bin/install -c -m 644 .//supa_audit.control '/usr/share/postgresql/12.9/extension/'
/usr/bin/install -c -m 644 .//supa_audit--0.1.0--0.2.0.sql .//supa_audit--0.2.3--0.3.0.sql .//supa_audit--0.2.2--0.2.3.sql .//supa_audit--0.2.1--0.2.2.sql .//supa_audit--0.2.0--0.2.1.sql .//supa_audit--0.3.0.sql  '/usr/share/postgresql/12.9/extension/'
Removing intermediate container 488e3a5126f6
 ---> 2f06818d7713
Successfully built 2f06818d7713
Successfully tagged supa_audit:foo
```

should we keep the extra `with_llvm=no` option?

**Comment by ZeroDeltaAlpha** [comment]
Thanks @olirice for the quick response, we are actually working with @sebastianwebber here to get your plugin integrated into stackgres 😄 .

**Comment by olirice** [comment]
> it looks like the solution is already present in https://github.com/supabase/supa_audit/issues/36#issue-1210028572 .

great!

>  we are actually working with @sebastianwebber here to get your plugin integrated into stackgres 😄

🚀 very cool!
